
name: CI


on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt -r backend/requirements-dev.txt

      - name: Run tests
        working-directory: backend
        env:
          DATABASE_URL: postgresql://app:app@127.0.0.1:1/appdb
        run: python -m pytest -q tests

  frontend-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend deps
        working-directory: frontend
        run: npm install --ignore-scripts

  build-images:
    needs: [test-backend, frontend-install]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t tpdevops-backend:ci ./backend

      - name: Build frontend image
